"""set name and series

Revision ID: 1d9caa4ab373
Revises: bfa4b0a8de4b
Create Date: 2021-12-16 21:52:05.058724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9caa4ab373'
down_revision = 'bfa4b0a8de4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('set_series', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('set_series')
        batch_op.drop_column('set_name')

    # ### end Alembic commands ###
