"""card data

Revision ID: 4c78491e1285
Revises: 2feda55ef814
Create Date: 2021-12-14 19:21:58.451340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c78491e1285'
down_revision = '2feda55ef814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rarity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pokedex_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('normal_price_low', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('normal_price_mid', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('normal_price_high', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('normal_price_market', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('holofoil_price_low', sa.Float(sdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('holofoil_price_mid', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('holofoil_price_high', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('holofoil_price_market', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('reverse_holofoil_price_low', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('reverse_holofoil_price_mid', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('reverse_holofoil_price_high', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('reverse_holofoil_price_market', sa.Float(asdecimal=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('reverse_holofoil_price_market')
        batch_op.drop_column('reverse_holofoil_price_high')
        batch_op.drop_column('reverse_holofoil_price_mid')
        batch_op.drop_column('reverse_holofoil_price_low')
        batch_op.drop_column('holofoil_price_market')
        batch_op.drop_column('holofoil_price_high')
        batch_op.drop_column('holofoil_price_mid')
        batch_op.drop_column('holofoil_price_low')
        batch_op.drop_column('normal_price_market')
        batch_op.drop_column('normal_price_high')
        batch_op.drop_column('normal_price_mid')
        batch_op.drop_column('normal_price_low')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('url')
        batch_op.drop_column('image')
        batch_op.drop_column('pokedex_number')
        batch_op.drop_column('rarity')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
