"""followers

Revision ID: 898227e17036
Revises: dd0294c6a01f
Create Date: 2021-12-02 23:10:47.312816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898227e17036'
down_revision = 'dd0294c6a01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
